// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: user_rpc.proto

package server

import (
	"context"

	"fimCommunication-microService/fim_user/user_rpc/internal/logic"
	"fimCommunication-microService/fim_user/user_rpc/internal/svc"
	"fimCommunication-microService/fim_user/user_rpc/types/user"
)

type UsersServer struct {
	svcCtx *svc.ServiceContext
	user_rpc.UnimplementedUsersServer
}

func NewUsersServer(svcCtx *svc.ServiceContext) *UsersServer {
	return &UsersServer{
		svcCtx: svcCtx,
	}
}

func (s *UsersServer) UserCreate(ctx context.Context, in *user_rpc.UserCreateRequest) (*user_rpc.UserCreateResponse, error) {
	l := logic.NewUserCreateLogic(ctx, s.svcCtx)
	return l.UserCreate(in)
}
